version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      sentry:
        patterns:
          - "@sentry/*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
