/**
 * Supabase database type definitions.
 *
 * This file will be auto-generated by W2 after running:
 *   npx supabase gen types typescript --project-id <ref> > src/lib/supabase/types.ts
 *
 * For W1, this is a minimal stub so the Supabase clients compile correctly.
 * All tables and their columns are defined in supabase/migrations/0001_init.sql.
 */

export type Database = {
  public: {
    Tables: {
      tenants: {
        Row: {
          id: string;
          name: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          created_at?: string;
        };
      };
      users: {
        Row: {
          id: string;
          tenant_id: string;
          full_name: string;
          role: "analyst" | "admin";
          created_at: string;
        };
        Insert: {
          id: string;
          tenant_id: string;
          full_name: string;
          role: "analyst" | "admin";
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          full_name?: string;
          role?: "analyst" | "admin";
          created_at?: string;
        };
      };
      cases: {
        Row: {
          id: string;
          tenant_id: string;
          policy_number: string | null;
          policyholder_name: string | null;
          claim_type: "choque" | "robo" | "granizo" | "incendio" | "other" | null;
          status:
            | "procesando"
            | "listo"
            | "esperando"
            | "escalado"
            | "cerrado"
            | "recibido"
            | "info_faltante"
            | "confirmacion_pendiente"
            | "requiere_especialista"
            | "listo_para_core"
            | "enviado_a_core"
            | "error_core"
            | "no_relevante";
          confidence_min: number | null;
          assigned_to: string | null;
          channel: "email_sim" | "email" | "whatsapp_sim" | "whatsapp";
          created_at: string;
          updated_at: string | null;
          closed_at: string | null;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          policy_number?: string | null;
          policyholder_name?: string | null;
          claim_type?: "choque" | "robo" | "granizo" | "incendio" | "other" | null;
          status?:
            | "procesando"
            | "listo"
            | "esperando"
            | "escalado"
            | "cerrado"
            | "recibido"
            | "info_faltante"
            | "confirmacion_pendiente"
            | "requiere_especialista"
            | "listo_para_core"
            | "enviado_a_core"
            | "error_core"
            | "no_relevante";
          confidence_min?: number | null;
          assigned_to?: string | null;
          channel: "email_sim" | "email" | "whatsapp_sim" | "whatsapp";
          created_at?: string;
          updated_at?: string | null;
          closed_at?: string | null;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          policy_number?: string | null;
          policyholder_name?: string | null;
          claim_type?: "choque" | "robo" | "granizo" | "incendio" | "other";
          status?:
            | "procesando"
            | "listo"
            | "esperando"
            | "escalado"
            | "cerrado"
            | "recibido"
            | "info_faltante"
            | "confirmacion_pendiente"
            | "requiere_especialista"
            | "listo_para_core"
            | "enviado_a_core"
            | "error_core"
            | "no_relevante";
          confidence_min?: number | null;
          assigned_to?: string | null;
          channel?: "email_sim" | "email" | "whatsapp_sim" | "whatsapp";
          created_at?: string;
          updated_at?: string | null;
          closed_at?: string | null;
        };
      };
      raw_messages: {
        Row: {
          id: string;
          case_id: string;
          tenant_id: string;
          channel: string;
          from_addr: string | null;
          subject: string | null;
          body: string;
          received_at: string;
        };
        Insert: {
          id?: string;
          case_id: string;
          tenant_id: string;
          channel: string;
          from_addr?: string | null;
          subject?: string | null;
          body: string;
          received_at?: string;
        };
        Update: {
          id?: string;
          case_id?: string;
          tenant_id?: string;
          channel?: string;
          from_addr?: string | null;
          subject?: string | null;
          body?: string;
          received_at?: string;
        };
      };
      extracted_fields: {
        Row: {
          id: string;
          case_id: string;
          tenant_id: string;
          field_key: string;
          field_value: string;
          confidence: number;
          extracted_at: string;
        };
        Insert: {
          id?: string;
          case_id: string;
          tenant_id: string;
          field_key: string;
          field_value: string;
          confidence: number;
          extracted_at?: string;
        };
        Update: {
          id?: string;
          case_id?: string;
          tenant_id?: string;
          field_key?: string;
          field_value?: string;
          confidence?: number;
          extracted_at?: string;
        };
      };
      missing_docs: {
        Row: {
          id: string;
          case_id: string;
          tenant_id: string;
          doc_key: string;
          requested_at: string | null;
          satisfied_at: string | null;
        };
        Insert: {
          id?: string;
          case_id: string;
          tenant_id: string;
          doc_key: string;
          requested_at?: string | null;
          satisfied_at?: string | null;
        };
        Update: {
          id?: string;
          case_id?: string;
          tenant_id?: string;
          doc_key?: string;
          requested_at?: string | null;
          satisfied_at?: string | null;
        };
      };
      outbound_messages: {
        Row: {
          id: string;
          case_id: string;
          tenant_id: string;
          channel: string;
          template: string;
          rendered_body: string;
          status: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          case_id: string;
          tenant_id: string;
          channel: string;
          template: string;
          rendered_body: string;
          status?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          case_id?: string;
          tenant_id?: string;
          channel?: string;
          template?: string;
          rendered_body?: string;
          status?: string;
          created_at?: string;
        };
      };
      audit_log: {
        Row: {
          id: number;
          tenant_id: string;
          actor_id: string | null;
          event_type: string;
          target_type: string | null;
          target_id: string | null;
          payload: Record<string, unknown>;
          ip: string | null;
          ua: string | null;
          created_at: string;
        };
        Insert: {
          id?: number;
          tenant_id: string;
          actor_id?: string | null;
          event_type: string;
          target_type?: string | null;
          target_id?: string | null;
          payload?: Record<string, unknown>;
          ip?: string | null;
          ua?: string | null;
          created_at?: string;
        };
        Update: never; // audit_log is append-only
      };
      ai_usage: {
        Row: {
          id: number;
          tenant_id: string;
          user_id: string | null;
          model: string;
          prompt_tokens: number;
          completion_tokens: number;
          cost_usd: number;
          created_at: string;
        };
        Insert: {
          id?: number;
          tenant_id: string;
          user_id?: string | null;
          model: string;
          prompt_tokens: number;
          completion_tokens: number;
          cost_usd: number;
          created_at?: string;
        };
        Update: never; // usage is immutable
      };
      required_docs_config: {
        Row: {
          claim_type: string;
          doc_key: string;
          label_es: string;
          required: boolean;
        };
        Insert: {
          claim_type: string;
          doc_key: string;
          label_es: string;
          required: boolean;
        };
        Update: {
          claim_type?: string;
          doc_key?: string;
          label_es?: string;
          required?: boolean;
        };
      };
      gmail_poll_state: {
        Row: {
          id: string;
          gmail_account_email: string;
          history_id: string;
          last_polled_at: string | null;
          last_error: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          gmail_account_email: string;
          history_id?: string;
          last_polled_at?: string | null;
          last_error?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          gmail_account_email?: string;
          history_id?: string;
          last_polled_at?: string | null;
          last_error?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      claim_messages: {
        Row: {
          id: string;
          case_id: string;
          tenant_id: string;
          direction: "inbound" | "outbound";
          provider: string;
          provider_message_id: string | null;
          thread_id: string | null;
          from_addr: string;
          subject: string | null;
          body_text: string | null;
          body_html: string | null;
          headers: Record<string, unknown> | null;
          raw_payload: Record<string, unknown> | null;
          status: string;
          received_at: string;
        };
        Insert: {
          id?: string;
          case_id: string;
          tenant_id: string;
          direction: "inbound" | "outbound";
          provider: string;
          provider_message_id?: string | null;
          thread_id?: string | null;
          from_addr: string;
          subject?: string | null;
          body_text?: string | null;
          body_html?: string | null;
          headers?: Record<string, unknown> | null;
          raw_payload?: Record<string, unknown> | null;
          status?: string;
          received_at?: string;
        };
        Update: {
          id?: string;
          case_id?: string;
          tenant_id?: string;
          direction?: "inbound" | "outbound";
          provider?: string;
          provider_message_id?: string | null;
          thread_id?: string | null;
          from_addr?: string;
          subject?: string | null;
          body_text?: string | null;
          body_html?: string | null;
          headers?: Record<string, unknown> | null;
          raw_payload?: Record<string, unknown> | null;
          status?: string;
          received_at?: string;
        };
      };
      claim_attachments: {
        Row: {
          id: string;
          case_id: string;
          claim_message_id: string | null;
          tenant_id: string;
          storage_path: string;
          original_filename: string | null;
          content_type: string | null;
          size_bytes: number | null;
          rejected_reason: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          case_id: string;
          claim_message_id?: string | null;
          tenant_id: string;
          storage_path: string;
          original_filename?: string | null;
          content_type?: string | null;
          size_bytes?: number | null;
          rejected_reason?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          case_id?: string;
          claim_message_id?: string | null;
          tenant_id?: string;
          storage_path?: string;
          original_filename?: string | null;
          content_type?: string | null;
          size_bytes?: number | null;
          rejected_reason?: string | null;
          created_at?: string;
        };
      };
    };
    Views: Record<string, never>;
    Functions: {
      current_tenant_id: {
        Args: Record<string, never>;
        Returns: string;
      };
    };
    Enums: Record<string, never>;
  };
};
